---
title: "Banana Boat STA 199 Project"
subtitle: "STA 199 Project"
format: html
editor: visual
---

This project looks at the use of renewable energy in the United States in order to analyze trends in hopes of informing change that can help slow climate change. We used the data, which looks at different types of consumption and expenditure of each state, to compare the proportion of renewable energy usage nationally, regionally, and politically. Overall, we found that the use of renewable nationally is both low and only increasing slightly, but still not nearly enough to slow climate change. By region, our findings show that the Northeast has the highest use of renewable energy, while the South has the lowest. Additionally, by political party, we found that Democratic states use more renewable energy than Republican states. However, overall we found that each of these groupings was not a sufficient way to explain the trends in the proportion of renewable energy usage, as evidenced in our models' low adjusted r-squared values, as there are countless other interacting factors, shown by the high AIC on our models, including current events, economics, resource access, and population, all of which were limitations to our data set.
