<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Banana Boat STA 199 Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Banana Boat STA 199 Project</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presentation.pdf">Presentation</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page">Report</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-data" id="toc-introduction-data" class="nav-link active" data-scroll-target="#introduction-data"><strong>Introduction &amp; Data</strong></a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review"><strong>Literature Review</strong></a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><strong>Methodology</strong></a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><strong>Results</strong></a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Banana Boat STA 199 Project</h1>
<p class="subtitle lead">Report</p>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="introduction-data" class="level2">
<h2 class="anchored" data-anchor-id="introduction-data"><strong>Introduction &amp; Data</strong></h2>
<p>This data set comes from the CORGIS Dataset Project, which got this data from the US Energy Information Administration, a part of the US Government. This data has been collected by the US Energy Information Administration from 1960 to 2019 based on the consumption, production, expenditures, and price of different sources of energy by state.</p>
<p>The observations are of different states in different years and have variables for many energy sources, including coal, kerosene, geothermal, hydro, etc. There are also different variables for the production, consumption, expenditure, and price of these types of energy. For some of these, information was not available, in which case a 0 was reported.</p>
<p>There should be no ethical concerns about the data since the data is not specific to individuals and reports many types of used energy in the US.</p>
<p><em>Research question: On both a regional and national level, how has the proportion of renewable energy consumption relative to overall energy consumption changed over time, and has this shift been because of geographic, political, or other external factors?</em></p>
<p>As climate change continues to progress rapidly, it is important to move towards clean technology and renewable energy sources in order to save our earth while ensuring innovation. The United States of America has emerged as a leading renewable energy innovator in the world, which is a perfect study target for researchers who are interested in the implementation of renewable energy. Our team thinks that analyzing the energy usage of different states is a good way to see how our country is progressing toward the goal of slowing global warming on a local level. This research method will help policymakers and environmental engineers pinpoint the specific problems regarding renewable energy in our country and help us move towards a clean future of collaboration of all states.</p>
<p>Important definitions: The data set contains both categorical and quantitative variables. The categorical variables include “State”. The remaining columns, focusing on relevant facts regarding different uses of energy, are all quantitative.</p>
<p>Renewable energy: For our project, energy is considered renewable if it meets two criteria. First, the energy must be derived from a naturally occurring source. Additionally, the energy is naturally replenished at a higher rate than it is consumed/used.</p>
<p>Other energy sources: natural gas, coal, as well as any other sources of energy.</p>
<p>Groups of interest: states, regions, political parties, expenditures and consumption of renewable energy and other energy sources. Our goal is to study the effects of these aforementioned variables to learn about consumption habits and the technological specialization of different states.</p>
</section>
<section id="literature-review" class="level2">
<h2 class="anchored" data-anchor-id="literature-review"><strong>Literature Review</strong></h2>
<p>Ratner, M., Bracmort, K., Brown, P., Campbell, R. J., Holt, M., Humphries, M., Pirog, R., &amp; Yacobucci, B. D. (2018, November 5). U.S. Energy in the 21st Century: A Primer. The Congressional Research Service. Retrieved March 10, 2023, from <a href="https://crsreports.congress.gov/product/pdf/R/R46723" class="uri">https://crsreports.congress.gov/product/pdf/R/R46723</a>.</p>
<p>This article dives into energy usage in the United States and goes into detail about recent trends. The text claims that, despite energy consumption remaining relatively constant, the U.S. has shifted away from non-renewable energy sources (oil and coal) and towards more renewable sources of energy. The article makes the claim that natural gas and renewable energy consumption has increased, oil and nuclear power consumption didn’t change and coal decreased. In the 21st century, renewable energy consumption has almost doubled, making its increasing importance obvious. Despite this, renewable energy still only makes up 11% of U.S. energy consumption.</p>
<p>One big difference between our data and the article that we want to expand upon is that the article talks about general trends in the U.S., but doesn’t discuss any of the costs. Also, the article doesn’t take into account the factors that could provide reasoning for differences in renewable energy usage such as region or political affiliation, which we looked into.</p>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology"><strong>Methodology</strong></h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0      ✔ purrr   1.0.0 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.5.0 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──

✔ broom        1.0.2     ✔ rsample      1.1.1
✔ dials        1.1.0     ✔ tune         1.0.1
✔ infer        1.0.4     ✔ workflows    1.1.2
✔ modeldata    1.0.1     ✔ workflowsets 1.0.0
✔ parsnip      1.0.3     ✔ yardstick    1.1.0
✔ recipes      1.0.3     

── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()
• Use tidymodels_prefer() to resolve common conflicts.

Rows: 3060 Columns: 84
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): State
dbl (83): Year, Production.Coal, Consumption.Commercial.Coal, Consumption.Co...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p><strong>National</strong>:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/renew-energy-graph-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, we use a dot plot to demonstrate the change over time of renewable consumption. Additionally, we added a line of best fit in order to best see how the consumption changed over time. This graph demonstrates that since 1960, there has been an overall increase in the proportion of renewable energy used from about 0.0008 to 0.0025. While this increase is good, the proportion of energy that is renewable is still remarkably low.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term          estimate  std.error statistic       p.value
  &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;
1 (Intercept) -0.0343    0.00488        -7.03 0.00000000262
2 Year         0.0000176 0.00000245      7.19 0.00000000142</code></pre>
</div>
</div>
<p><span class="math inline">\(\widehat{prop\_renewable\_national} = -3.43e^{-2}+1.76e^{-5} * Year\)</span></p>
<p>Interpret our model:</p>
<p>We estimate the proportion of renewable energy the US uses to increase <span class="math inline">\(1.76e^{-05}\)</span> every year.</p>
<p>Model fit:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4710977</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4619787</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -788.182</code></pre>
</div>
</div>
<p>Predicting renewable energy proportions in 2030:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    .pred
    &lt;dbl&gt;
1 0.00148</code></pre>
</div>
</div>
<p>This model allows us to predict how the use of renewable energy will change in the upcoming years based on the current data. It also allows us to predict, based on this data, what our proportion of renewable energy usage will be in future years, such as 2030.</p>
<p><strong>Regional comparison</strong>:</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/south-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/northeast-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/west-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/midwest-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>*The scale on the y axis of each of the regional graphs differs based on the magnitude of its respective data, so when comparing these graphs take this into consideration as the data in certain graphs represent smaller changes despite how it may look on the graph.</p>
<p>These graphs allow us to visualize and compare the states by region. The states were grouped into four regions, Northeast, West, Midwest, and South. Overall, these graphs show that the Northeast as a region has the highest proportion of renewable energy, followed by the West, the South, then the Midwest. There are a few notable outliers, especially Hawaii in the West, which has the highest renewable energy output of any state, and a spike in 2000 from North Carolina and Tennessee in the South.</p>
<p>Regional model:</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  term                     estimate std.error statistic  p.value
  &lt;chr&gt;                       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)          -0.0505      0.0250      -2.02   0.0434  
2 Year                  0.0000257   0.0000126    2.05   0.0408  
3 regionnortheast       0.129       0.0331       3.89   0.000104
4 regionsouth           0.0461      0.0365       1.26   0.207   
5 regionwest            0.000850    0.0395       0.0215 0.983   
6 Year:regionnortheast -0.0000631   0.0000166   -3.79   0.000152
7 Year:regionsouth     -0.0000234   0.0000183   -1.27   0.202   
8 Year:regionwest      -0.000000296 0.0000199   -0.0149 0.988   </code></pre>
</div>
</div>
<p><span class="math inline">\(\widehat{prop\_renewable} = -5.05e^{-2}+2.57e^{-5} * Year + 1.29e^{-1}*northeast + 4.61e^{-2} * south + 8.50e^{-4} * west - 6.31e^{-5}*Year*northeast -2.34e^{-5}*Year*south -2.96e^{-7}*Year*west\)</span></p>
<p>{1 if south; 0 if not} {1 if northeast; 0 if not} {1 if west; 0 if not}</p>
<p>Interpreting our model:</p>
<p>Holding region constant, we estimate the proportion of renewable energy a state uses to increase <span class="math inline">\(2.57e^{-05}\)</span> every year.</p>
<p>Holding year constant, we estimate the proportion of renewable energy a state uses to increase <span class="math inline">\(0.475\)</span> for the <strong>Northeast</strong> region</p>
<p>Holding year constant, we estimate the proportion of renewable energy a state uses to increase <span class="math inline">\(0.624\)</span> for the <strong>South</strong> region.</p>
<p>Holding year constant, we estimate the proportion of renewable energy a state uses to increase <span class="math inline">\(0.156\)</span> for the <strong>West</strong> region.</p>
<p>Holding year constant, we estimate the proportion of renewable energy a state uses to decrease <span class="math inline">\(0.683\)</span> for the <strong>Midwest</strong> region.</p>
<p>We estimate the proportion of renewable energy a state in the <strong>Northeast</strong> uses to decrease <span class="math inline">\(0.043\)</span> each year.</p>
<p>We estimate the proportion of renewable energy a state in the <strong>South</strong> uses to decrease <span class="math inline">\(0.016\)</span> each year.</p>
<p>We estimate the proportion of renewable energy a state in the <strong>West</strong> uses to decrease <span class="math inline">\(0.003\)</span> each year.</p>
<p>Model fit:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09329481</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09026091</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -16233.92</code></pre>
</div>
</div>
<p>Predicting renewable energy proportions in 2030:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    .pred
    &lt;dbl&gt;
1 0.00195</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
     .pred
     &lt;dbl&gt;
1 0.000329</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    .pred
    &lt;dbl&gt;
1 0.00229</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    .pred
    &lt;dbl&gt;
1 0.00170</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
     .pred
     &lt;dbl&gt;
1 0.000329</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    .pred
    &lt;dbl&gt;
1 0.00229</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    .pred
    &lt;dbl&gt;
1 0.00170</code></pre>
</div>
</div>
<p>Similar to the national model, this model allows us to predict how the use of renewable energy will change in the upcoming years based on the current data for each region. It also allows us to predict, based on this data, what our proportion of renewable energy usage will be in future years for these regions, such as in 2030.</p>
<p><strong>Political Affiliations:</strong></p>
<div class="cell">

</div>
<p>These states were grouped by democratic and republic based on how they voted in 2018 because this dataset ended in 2019, and 2018 was the most recent nationwide voting before that.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/deomcrat-graph-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/republican-graph-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>*The scales on the y axis of the democratic graph is approximately 10 times greater than that of the republican graph, so when comparing take this into consideration as the data in the democratic graph represents more change than the republican graph.</p>
<p>These graphs allow us to visualize and compare the proportion of renewable energy used by republican and democratic states. These graphs demonstrate that overall the democratic states use more renewable energy than republican states. There are a few notable outliers, specifically Maine in the democratic states and Idaho in the republican states.</p>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term                          estimate std.error statistic p.value
  &lt;chr&gt;                            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)                -0.0141     0.109        -0.129   0.897
2 Year                        0.00000854 0.0000549     0.156   0.876
3 partyRepublican State       0.0185     0.110         0.168   0.867
4 Year:partyRepublican State -0.00000992 0.0000553    -0.179   0.858</code></pre>
</div>
</div>
<p><span class="math inline">\(\widehat{prop\_renewable}=-1.41e^{-2}+8.54e^{-6}*Year+1.85e^{-2}*Republican State - 9.92e^{-6}*Year*Republican State\)</span></p>
<p>{1 if Republican state; 0 if Democratic state}</p>
<p>Holding party constant, we estimate the proportion of renewable energy a state uses to increase <span class="math inline">\(8.54e^{-06}\)</span> every year.</p>
<p>Holding year constant, we estimate the proportion of renewable energy a state uses to increase <span class="math inline">\(0.250\)</span> for the Democratic states.</p>
<p>we estimate the proportion of renewable energy a state uses to decrease <span class="math inline">\(0.025\)</span> for the Republican states each year.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001031103</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.0003987193</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -16038.41</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    .pred
    &lt;dbl&gt;
1 0.00328</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
    .pred
    &lt;dbl&gt;
1 0.00161</code></pre>
</div>
</div>
<p>Similar to the previous models, this model allows us to predict how the use of renewable energy will change in the upcoming years based on the current data for the states affiliated with each political party. It also allows us to predict, based on this data, what our proportion of renewable energy usage will be in future years for these parties, such as in 2030.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results"><strong>Results</strong></h2>
<p>Our data confirms several important pieces of information about renewable energy usage in the United States. The first is that on a national level, we expect the proportion of renewable energy to continue increasing each year, with a predicted 2030 proportion of 0.0015. However, with that being said we also calculated a low adjusted r-squared value of 0.46, showing a low correlation between a rising proportion of renewable energy and year. This proportion of 0.0015 is very low for the amount of total energy in the US that is renewable. While it is continually increasing, it is increasing very slowly. Therefore, this further proves that big changes need to be made in the use of renewable energy in the United States if we want to slow or stop climate change.</p>
<p>Additionally, on regional levels, we’ve predicted that the NE will have the highest proportion of renewable energy in the year 2030 at 0.0023, compared to the lowest region, the south, which is predicted to be at 0.00033. Yet, once again, our adjusted r-squared value of 0.09 shows that our estimation is only that, and there is significantly low correlation between the proportion of renewable energy versus year and region, even less than on a national level. Even though this model has a low R squared, there is correlation between region and renewable energy usage. This is most likely a cause of cultural factors in these different regions. These cultural differences manifest because of differing beliefs about climate change as well as different economies and areas of employment. Another factor to consider when looking at regions is accessibility to renewable energy. However, since the Midwest is the region that produces the most renewable energy, but it only has the third-highest proportion of renewable energy, it is unlikely that this is a large factor in the usage of renewable energy.</p>
<p>Lastly, when we divided the states based on political affiliation, we found that states who are democratic overall had a higher proportion of renewable energy usage than Republican states and are increasing at a faster rate as well. However, we found an adjusted r-squared of -0.0004, showing that there is a very high level of variability that cannot be explained by this model. Therefore, while policy based on party likely has an effect, there are many other variables at play to explain the usage of renewable energy.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>A big takeaway from our models is that the regional AIC came out to be -16,233.92, while the political affiliation AIC came out to -16038.41, showing that there are a lot of other factors not present in our data set which need to be taken into account and can better explain a correlation to the proportion of renewable energy. Even on a national level, using time as a predictor of the proportion of renewable energy resulted in an AIC of -788.18, so overall the models we have do not represent a meaningful connection to the proportion. This can be summed up to some of the limitations of our data set, with the first being its lack of data on a smaller scope. The information it contains does not go beyond a state level, and we believe that local factors such as resources, energy rates, and metropolitan population can better explain the choice to use renewable energy. Additionally, current events which could potentially affect the energy market and decision-making about energy sources are also not included in the data set, which we believe is another significant factor left out. These have manifested in many different ways since 1960, including oil crises, economic crises, and job availability. All of these factors and many more create a huge amount of variability in this data set, making it difficult to predict the future usage of renewable energy.</p>
<p>Overall, there is not one factor we can look at in order to improve renewable energy usage, instead, we need to look at climate change as a whole. If we can increase the amount of education and discourse about climate change, we can hope to bring it into the forefront of people’s minds. That way they will consider the effects of everything they do economically, politically, and in their personal lives on the effect on the climate. It is imperative that we work towards a higher national usage of renewable energy at every level in order to save our planet.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>